"""sync columns

Revision ID: aaeeae02be22
Revises: 
Create Date: 2025-10-18 23:19:01.758822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaeeae02be22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_entries_day'))

    op.drop_table('menu_entries')
    op.drop_table('menu_ingredients')
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_resident_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_resident_last_name'), ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resident_last_name'))
        batch_op.drop_index(batch_op.f('ix_resident_first_name'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('menu_ingredients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('menu_entry_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['menu_entry_id'], ['menu_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.DATE(), nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'meal_type', name=op.f('uq_menu_day_meal'))
    )
    with op.batch_alter_table('menu_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_entries_day'), ['day'], unique=False)

    # ### end Alembic commands ###
